<?php if (isset($this->errors)): ?>
<p class="navbar-text pull-left text-error login_error"><?= $this->errors ?>
    <?php if (isset($this->attempts)) : ?>
        <?php $attempt = 3 - $this->attempts ?>
        <?php if ($attempt === 1) : ?>
            - Last try
        <?php else: ?>
            - <?= $attempt ?> more attempts
        <?php endif; ?>
    <?php endif; ?></p>
<?php endif; ?>

<form method="POST" action="<?= $this->url('login') ?>" class="navbar-form pull-right">
    <input class="input-small js_login_username" type="text" name="login" placeholder="Username" />
    <input class="input-small js_login_password" type="password" name="password" placeholder="Password" />
    <input type="submit" class="btn btn-primary js_login_submit" />
</form>