<form class="form-horizontal" action="<?= $this->url('login'); ?>" method="POST">
    <fieldset>
        <legend>Login</legend>
        <div class="control-group">
            <label class="control-label" for="email">Username:</label>
            <div class="controls">
                <input id="email" class="input-large" type="text" name="login" placeholder="Username" />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="password">Password:</label>
            <div class="controls">
                <input id="password" class="input-large" type="password" name="password" placeholder="Password" />
            </div>
        </div>
        <div class="form-actions">
            <input class="btn btn-primary" type="submit" value="Login" />
        </div>
    </fieldset>
</form>
<p>Not register ? You can register <a href="<?= $this->url('register') ?>">here!</a></p>
