<?php

$title = 'Add new image';
$this->headTitle($title);
?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('image-add'));
$form->prepare();

echo $this->form()->openTag($form);
?>
<fieldset>
<legend><?php echo $this->escapeHtml($title); ?></legend>
<?php $errors = $form->get('image')->getMessages(); ?>
<div class="control-group <?php if (!empty($errors)) : ?>error text-error<?php endif; ?>">
    <div class="controls">
        <?= $this->formElementErrors($form->get('image')); ?>
        <div class="input-prepend">
            <?= $this->formFile($form->get('image')); ?>
        </div>
    </div>
</div>
<input type="submit" value="Add" class="btn btn-primary"/>
</fieldset>
<?php
echo $this->form()->closeTag();

