<?php

$title = 'Add new image';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('image-add'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo "<label>Public:</label>";
echo $this->formRadio($form->get('public'), 'prepend');
echo $this->formRow($form->get('order'));
echo $this->formRow($form->get('file'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

