<h2 class="span12"><?php echo $this->randomGallery->getOwner()->getUsername(); ?>'s gallery</h2>

<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Others</li>
<?php foreach($this->allGallery as $gallery) : ?>
    <?php $username = $gallery->getOwner()->getUsername(); ?>
    <li>
        <a href="<?= $this->url('gallery-show', array(
            'username' => $username)); ?>"><?= $username; ?></a>
    </li>
<?php endforeach; ?>
    </ul>
  </div><!--/.well -->
</div>

<div class="span9">
<?php $i = 0; ?>
<?php foreach($this->randomGallery->getImages() as $image) : ?>
    <?php if ($image->isPublic() || isset($owner) && $randomGallery->getOwner()->getId() == $owner->getId()): ?>
        <?php if ($i == 0): ?>
            <div class="row">
        <?php endif; ?>
            <div class="box span3">
                <img style="width:  200px;" src="../uploads/images/<?= $image->getPath(); ?>" alt="image"/><br />
                <span><b>Create :</b> <?= $image->getCreateAt()->format('Y-m-d H:i:s'); ?></span><br />
                <span><b>Size :</b> <?= $image->getWidth() ?>px / <?= $image->getHeight() ?>px</span>
                <?php if (isset($owner) && $randomGallery->getOwner()->getId() == $owner->getId()): ?>
                <form action="<?= $this->url('image-update') ?>" method="POST">
                        <label><b>Order:</b></label>
                        <input type="hidden" name="id" value="<?= $image->getId() ?>"/>
                        <input type="number" class="input-small" name="order" value="<?= $image->getOrder() ?>"/>
                        <input class="btn btn-primary btn-small" type="submit" name="submit" value="Update"/>
                    </form>

                    <form action="<?= $this->url('image-remove') ?>" method="POST">
                        <input type="hidden" name="id" value="<?= $image->getId() ?>"/>
                        <input class="btn btn-danger btn-small js_image_remove" type="submit" name="submit" value="Remove"/>
                    </form>
                <?php endif; ?>
            </div>
        <?php if ($i == 2): ?>
            </div>
            <?php $i = -1; ?>
        <?php endif; ?>

        <?php $i++; ?>
    <?php endif; ?>
<?php endforeach; ?>
</div>
