<h2><?php echo $this->randomGallery->getOwner()->getUsername(); ?>'s gallery</h2>

<p>Other</p>

<ol>
<?php foreach($this->allGallery as $gallery) : ?>
    <?php $username = $gallery->getOwner()->getUsername(); ?>
    <li>
        <a href="<?= $this->url('gallery-show', array(
            'username' => $username)); ?>"><?= $username; ?></a>
    </li>
<?php endforeach; ?>
</ol>

<table class="table">
    <tbody>
        <?php foreach($this->randomGallery->getImages() as $image) : ?>
            <?php /* display image */ ?>
        <?php endforeach; ?>
    </tbody>
</table>

