<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>">Home</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li><a></a></li>
                        </ul>
                        <?php $userSession = new \Zend\Session\Container('user'); ?>
                        <?php if (!$userSession->offsetExists('user')) : ?>
                        <form class="navbar-form pull-right" action="<?= $this->url('login'); ?>" method="POST">
                            <input class="input-small" type="text" name="login" placeholder="Login" />
                            <input class="input-small" type="password" name="password" placeholder="Password" />
                            <input class="btn  btn-primary" type="submit" />
                        </form>
                        <p class="navbar-text pull-left">
                            <?php if (!isset($this->viewModel()->getCurrent()->getChildren()[0]->noDisplayWell)) : ?>
                                Not register ? you can register <a href="<?= $this->url('register'); ?>">here!</a>
                            <?php endif; ?>
                        </p>
                        <?php else : ?>
                            <a class="btn btn-primary pull-right" href="<?= $this->url('logout'); ?>">logout</a>

                        <?php endif; ?>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">

            <?php
            $currentView = $this->viewModel()->getCurrent()->getChildren()[0];
            if (isset($currentView->flashMessages) && count($currentView->flashMessages)) : ?>
                <ul class="flashMessages">
                    <?php foreach ($currentView->flashMessages as $fMessage) : ?>
                    <li><?php echo $fMessage; ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>Lazarecki Benjamin - INSSET</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
