<?php
$this->headTitle("Register");
$form = $this->form;
$form->setAttribute('action', $this->url('register'));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

echo $this->form()->openTag($form);
?>
<legend>Registration</legend>
<?php $errors = $form->get('email')->getMessages(); ?>
<div class="control-group <?php if (!empty($errors)) : ?>error text-error<?php endif; ?>">
    <label class="control-label" for="email">Email:</label>
    <div class="controls">
        <?= $this->formElementErrors($form->get('email')); ?>
        <div class="input-prepend">
            <span class="add-on">@</span>
            <?= $this->formInput($form->get('email')); ?>
        </div>
    </div>
</div>

<?php $errors = $form->get('username')->getMessages(); ?>
<div class="control-group <?php if (!empty($errors)) : ?>error text-error<?php endif; ?>">
    <label class="control-label" for="username">Username:</label>
    <div class="controls">
        <?= $this->formElementErrors($form->get('username')); ?>
        <div class="input-prepend">
            <span class="add-on">abc</span>
            <?= $this->formInput($form->get('username')); ?>
        </div>
    </div>
</div>

<?php $errors = $form->get('age')->getMessages(); ?>
<div class="control-group <?php if (!empty($errors)) : ?>error text-error<?php endif; ?>">
    <label class="control-label" for="age">Age:</label>
    <div class="controls">
        <?= $this->formElementErrors($form->get('age')); ?>
        <div class="input-prepend">
            <span class="add-on">123</span>
            <?= $this->formInput($form->get('age')); ?>
        </div>
    </div>
</div>

<?php $errors = $form->get('captcha')->getMessages(); ?>
<div class="control-group <?php if (!empty($errors)) : ?>error text-error<?php endif; ?>">
    <label class="control-label" for="age">Captcha:</label>
    <div class="controls">
        <?= $this->formElementErrors($form->get('captcha')); ?>
        <?= $this->formCaptchaFiglet($form->get('captcha')); ?>
    </div>
</div>

<div class="control-group">
    <div class="form-actions">
        <?= $this->formInput($form->get('submit')); ?>
    </div>
</div>

<?= $this->form()->closeTag($form); ?>



